### ISSUE TITLE
Please help me, Error occurred on my condition

### ISSUE THREAD

**Issue by zxsoft** [bearice/pptp2http#1]
LINK UP
PPPD_PID=1
PPPLOGNAME=root
PPP_IPPARAM=pptp
SPEED=38400
IPREMOTE=12.12.12.254
PPP_SPEED=38400
IFNAME=ppp0
PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
DNS2=119.29.29.29
DNS1=114.114.114.114
PPP_LOCAL=12.12.12.11
PWD=/
CALL_FILE=pptp
PPP_REMOTE=12.12.12.254
SHLVL=1
PPP_TTYNAME=
USEPEERDNS=1
PPP_TTY=
ORIG_UID=0
IPLOCAL=12.12.12.11
PPP_IFACE=ppp0
_=/usr/bin/env
2018/11/30 07:37:55| WARNING: (B) '127.0.0.1' is a subnetwork of (A) '127.0.0.1'
2018/11/30 07:37:55| WARNING: because of this '127.0.0.1' is ignored to keep splay tree searching predictable
2018/11/30 07:37:55| WARNING: You should probably remove '127.0.0.1' from the ACL named 'localhost'
2018/11/30 07:37:55| WARNING: (B) '127.0.0.1' is a subnetwork of (A) '127.0.0.1'
2018/11/30 07:37:55| WARNING: because of this '127.0.0.1' is ignored to keep splay tree searching predictable
2018/11/30 07:37:55| WARNING: You should probably remove '127.0.0.1' from the ACL named 'localhost'
/etc/ppp/ip-up.local: line 33: curl: command not found
error: fromjson is not defined
.status="CONNECTED"|.external=($ext|fromjson)|.dns1=$dns1|.dns2=$dns2|.tunnel_ip=$ip
                                    ^^^^^^^^
1 compile error

**Comment by zxsoft** [comment]
OS: Ubuntu 18.04.1
Command: 
docker run -d \
  --device /dev/ppp \
  --cap-add=net_admin \
  --name pptp1 \
  -v $HOME/pptp_status:/data \
  bearice/pptp2http \
  /init.sh $SERVER $USER $PASSWD

I've already changed the correct $SERVER, $USER, and $PASSWD

**Comment by bearice** [comment]
> error: fromjson is not defined

this may caused by an incompatible version of jq, please make sure you have jq 1.4 or higher

**Comment by bearice** [comment]
> /etc/ppp/ip-up.local: line 33: curl: command not found

also the log shows that you don't have curl installed

**Comment by bearice** [comment]
@zxsoft sorry for the trouble, I made this years age and not tested it before pushing to a public repo, the old image is based on a private image and may not work, please feel free to build your own images or you may try the one i just pushed
